version: '2'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: mglthours_elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - es
    networks:
      - esnet

volumes:
  elastic-data:
    driver: local

networks:
  esnet:
